# .github/workflows/update_weights.yml
name: Обновить веса моделей

on:
  schedule:
    - cron: '0 0 * * *'   # каждый день в 00:00 UTC
  workflow_dispatch:      # кнопка «Run workflow» вручную

jobs:
  train-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Train models
        run: |
          python train_all_models.py

      - name: Commit & push weights
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout weights || git checkout --orphan weights
          git rm -rf . || true          # очищаем предыдущий коммит
          mkdir -p weights
          mv weights/* ./ 2>/dev/null || true
          git add .
          git commit -m "авто: обновлены веса моделей $(date -u +%F_%T)" || exit 0
          git push origin weights --force
